name: wban_monitor
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.10.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # --- ADDED DEPENDENCIES HERE ---
  flutter_map: ^6.0.0   # For the OpenStreetMap display
  latlong2: ^0.9.0      # For handling coordinates
  # -------------------------------

  cupertino_icons: ^1.0.2
  firebase_core: ^4.2.1
  firebase_database: ^12.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true